var searchData=
[
  ['_40359',['@359',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal_1_1@359.html',1,'TrilinosWrappers::internal']]],
  ['_40361',['@361',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@361.html',1,'TrilinosWrappers']]],
  ['_40626',['@626',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@626.html',1,'TrilinosWrappers']]],
  ['_40631',['@631',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@631.html',1,'TrilinosWrappers']]],
  ['_40632',['@632',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@632.html',1,'TrilinosWrappers']]],
  ['_40633',['@633',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal_1_1@633.html',1,'TrilinosWrappers::internal']]],
  ['_40634',['@634',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@634.html',1,'TrilinosWrappers']]],
  ['_40634',['@634',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal_1_1@634.html',1,'TrilinosWrappers::internal']]],
  ['_40635',['@635',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@635.html',1,'TrilinosWrappers']]],
  ['_40636',['@636',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@636.html',1,'TrilinosWrappers']]],
  ['_40637',['@637',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1@637.html',1,'TrilinosWrappers']]],
  ['blocklinearoperator',['BlockLinearOperator',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal_1_1BlockLinearOperator.html',1,'TrilinosWrappers::internal']]],
  ['internal',['internal',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceThreads_1_1internal.html',1,'Threads']]],
  ['internal',['internal',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal.html',1,'TrilinosWrappers']]],
  ['internal',['internal',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTensorAccessors_1_1internal.html',1,'TensorAccessors']]],
  ['internals',['internals',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internals.html',1,'TrilinosWrappers']]],
  ['linearoperator',['LinearOperator',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal_1_1LinearOperator.html',1,'TrilinosWrappers::internal']]],
  ['mpi',['MPI',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1MPI.html',1,'TrilinosWrappers']]],
  ['preconditionamg',['PreconditionAMG',['../namespaceTrilinosWrappers_1_1PreconditionAMG.html',1,'TrilinosWrappers']]],
  ['preconditionamgmuelu',['PreconditionAMGMueLu',['../namespaceTrilinosWrappers_1_1PreconditionAMGMueLu.html',1,'TrilinosWrappers']]],
  ['preconditionbase',['PreconditionBase',['../namespaceTrilinosWrappers_1_1PreconditionBase.html',1,'TrilinosWrappers']]],
  ['preconditionblockjacobi',['PreconditionBlockJacobi',['../namespaceTrilinosWrappers_1_1PreconditionBlockJacobi.html',1,'TrilinosWrappers']]],
  ['preconditionblocksor',['PreconditionBlockSOR',['../namespaceTrilinosWrappers_1_1PreconditionBlockSOR.html',1,'TrilinosWrappers']]],
  ['preconditionblockssor',['PreconditionBlockSSOR',['../namespaceTrilinosWrappers_1_1PreconditionBlockSSOR.html',1,'TrilinosWrappers']]],
  ['preconditionblockwisedirect',['PreconditionBlockwiseDirect',['../namespaceTrilinosWrappers_1_1PreconditionBlockwiseDirect.html',1,'TrilinosWrappers']]],
  ['preconditionchebyshev',['PreconditionChebyshev',['../namespaceTrilinosWrappers_1_1PreconditionChebyshev.html',1,'TrilinosWrappers']]],
  ['preconditionic',['PreconditionIC',['../namespaceTrilinosWrappers_1_1PreconditionIC.html',1,'TrilinosWrappers']]],
  ['preconditionidentity',['PreconditionIdentity',['../namespaceTrilinosWrappers_1_1PreconditionIdentity.html',1,'TrilinosWrappers']]],
  ['preconditionilu',['PreconditionILU',['../namespaceTrilinosWrappers_1_1PreconditionILU.html',1,'TrilinosWrappers']]],
  ['preconditionilut',['PreconditionILUT',['../namespaceTrilinosWrappers_1_1PreconditionILUT.html',1,'TrilinosWrappers']]],
  ['preconditionjacobi',['PreconditionJacobi',['../namespaceTrilinosWrappers_1_1PreconditionJacobi.html',1,'TrilinosWrappers']]],
  ['preconditionsor',['PreconditionSOR',['../namespaceTrilinosWrappers_1_1PreconditionSOR.html',1,'TrilinosWrappers']]],
  ['preconditionssor',['PreconditionSSOR',['../namespaceTrilinosWrappers_1_1PreconditionSSOR.html',1,'TrilinosWrappers']]],
  ['solverbase',['SolverBase',['../namespaceTrilinosWrappers_1_1SolverBase.html',1,'TrilinosWrappers']]],
  ['solverbicgstab',['SolverBicgstab',['../namespaceTrilinosWrappers_1_1SolverBicgstab.html',1,'TrilinosWrappers']]],
  ['solvercg',['SolverCG',['../namespaceTrilinosWrappers_1_1SolverCG.html',1,'TrilinosWrappers']]],
  ['solvercgs',['SolverCGS',['../namespaceTrilinosWrappers_1_1SolverCGS.html',1,'TrilinosWrappers']]],
  ['solverdirect',['SolverDirect',['../namespaceTrilinosWrappers_1_1SolverDirect.html',1,'TrilinosWrappers']]],
  ['solvergmres',['SolverGMRES',['../namespaceTrilinosWrappers_1_1SolverGMRES.html',1,'TrilinosWrappers']]],
  ['solvertfqmr',['SolverTFQMR',['../namespaceTrilinosWrappers_1_1SolverTFQMR.html',1,'TrilinosWrappers']]],
  ['sparsematrix',['SparseMatrix',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1internal_1_1SparseMatrix.html',1,'TrilinosWrappers::internal']]],
  ['sparsematrixiterators',['SparseMatrixIterators',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1SparseMatrixIterators.html',1,'TrilinosWrappers']]],
  ['sparsitypatterniterators',['SparsityPatternIterators',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1SparsityPatternIterators.html',1,'TrilinosWrappers']]],
  ['table_3c_202_2c_20smartpointer_3c_20blocktype_2c_20blockmatrixbase_3c_20petscwrappers_3a_3asparsematrix_20_3e_20_3e_20_3e',['Table&lt; 2, SmartPointer&lt; BlockType, BlockMatrixBase&lt; PETScWrappers::SparseMatrix &gt; &gt; &gt;',['../namespaceTable_3_012_00_01SmartPointer_3_01BlockType_00_01BlockMatrixBase_3_01PETScWrappers_1_1SparseMatrix_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20_3a_3afefacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; ::FEFaceValues&lt; dim, spacedim &gt; &gt; &gt;',['../namespaceTable_3_013_00_01std__cxx11_1_1shared__ptr_3_01_1_1FEFaceValues_3_01dim_00_01spacedim_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20_3a_3afesubfacevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; ::FESubfaceValues&lt; dim, spacedim &gt; &gt; &gt;',['../namespaceTable_3_013_00_01std__cxx11_1_1shared__ptr_3_01_1_1FESubfaceValues_3_01dim_00_01spacedim_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20_3a_3afevalues_3c_20dim_2c_20spacedim_20_3e_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; ::FEValues&lt; dim, spacedim &gt; &gt; &gt;',['../namespaceTable_3_013_00_01std__cxx11_1_1shared__ptr_3_01_1_1FEValues_3_01dim_00_01spacedim_01_4_01_4_01_4.html',1,'']]],
  ['table_3c_203_2c_20std_5fcxx11_3a_3ashared_5fptr_3c_20fevaluestype_20_3e_20_3e',['Table&lt; 3, std_cxx11::shared_ptr&lt; FEValuesType &gt; &gt;',['../namespaceTable_3_013_00_01std__cxx11_1_1shared__ptr_3_01FEValuesType_01_4_01_4.html',1,'']]],
  ['table_3c_204_2c_20internal_3a_3amatrixfreefunctions_3a_3ashapeinfo_3c_20number_20_3e_20_3e',['Table&lt; 4, internal::MatrixFreeFunctions::ShapeInfo&lt; Number &gt; &gt;',['../namespaceTable_3_014_00_01internal_1_1MatrixFreeFunctions_1_1ShapeInfo_3_01Number_01_4_01_4.html',1,'']]],
  ['tablehandler',['TableHandler',['../namespaceTableHandler.html',1,'']]],
  ['tensoraccessors',['TensorAccessors',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTensorAccessors.html',1,'']]],
  ['tensorproductpolynomials_3c_20dim_2c_20polynomials_3a_3apiecewisepolynomial_3c_20double_20_3e_20_3e',['TensorProductPolynomials&lt; dim, Polynomials::PiecewisePolynomial&lt; double &gt; &gt;',['../namespaceTensorProductPolynomials_3_01dim_00_01Polynomials_1_1PiecewisePolynomial_3_01double_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3alist_3c_20std_3a_3apair_3c_20bool_2c_20alignedvector_3c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e_20_3e_20_3e',['ThreadLocalStorage&lt; std::list&lt; std::pair&lt; bool, AlignedVector&lt; VectorizedArray&lt; Number &gt; &gt; &gt; &gt; &gt;',['../namespaceThreadLocalStorage_3_01std_1_1list_3_01std_1_1pair_3_01bool_00_01AlignedVector_3_01Vect2d47d683f451e5a11e29922e18312970.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3astack_3c_20std_3a_3astring_20_3e_20_3e',['ThreadLocalStorage&lt; std::stack&lt; std::string &gt; &gt;',['../namespaceThreadLocalStorage_3_01std_1_1stack_3_01std_1_1string_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3avector_3c_20double_20_3e_20_3e',['ThreadLocalStorage&lt; std::vector&lt; double &gt; &gt;',['../namespaceThreadLocalStorage_3_01std_1_1vector_3_01double_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_3a_3avector_3c_20mu_3a_3aparser_20_3e_20_3e',['ThreadLocalStorage&lt; std::vector&lt; mu::Parser &gt; &gt;',['../namespaceThreadLocalStorage_3_01std_1_1vector_3_01mu_1_1Parser_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20std_5fcxx11_3a_3ashared_5fptr_3c_20std_3a_3aostringstream_20_3e_20_3e',['ThreadLocalStorage&lt; std_cxx11::shared_ptr&lt; std::ostringstream &gt; &gt;',['../namespaceThreadLocalStorage_3_01std__cxx11_1_1shared__ptr_3_01std_1_1ostringstream_01_4_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20typename_20dofhandlertype_3a_3aactive_5fcell_5fiterator_20_3e',['ThreadLocalStorage&lt; typename DoFHandlerType::active_cell_iterator &gt;',['../namespaceThreadLocalStorage_3_01typename_01DoFHandlerType_1_1active__cell__iterator_01_4.html',1,'']]],
  ['threadlocalstorage_3c_20typename_20workstream_3a_3ainternal_3a_3aimplementation2_3a_3aiteratorrangetoitemstream_3a_3aitemtype_3a_3ascratchdatalist_20_3e',['ThreadLocalStorage&lt; typename WorkStream::internal::Implementation2::IteratorRangeToItemStream::ItemType::ScratchDataList &gt;',['../namespaceThreadLocalStorage_3_01typename_01WorkStream_1_1internal_1_1Implementation2_1_1Iterator1dc90e1dd33d14906eaf3807d3aa0024.html',1,'']]],
  ['threads',['Threads',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceThreads.html',1,'']]],
  ['timeroutput',['TimerOutput',['../namespaceTimerOutput.html',1,'']]],
  ['timestepbase_5ftria_5fflags',['TimeStepBase_Tria_Flags',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTimeStepBase__Tria__Flags.html',1,'']]],
  ['timestepping',['TimeStepping',['../namespaceTimeStepping_1_1TimeStepping.html',1,'TimeStepping']]],
  ['timestepping',['TimeStepping',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTimeStepping.html',1,'']]],
  ['triaaccessorexceptions',['TriaAccessorExceptions',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTriaAccessorExceptions.html',1,'']]],
  ['triangulation',['Triangulation',['../namespaceTriangulation.html',1,'']]],
  ['triangulation_3c_20dofhandler_3c_20dim_20_3e_3a_3adimension_2c_20dofhandler_3c_20dim_20_3e_3a_3aspace_5fdimension_20_3e',['Triangulation&lt; DoFHandler&lt; dim &gt;::dimension, DoFHandler&lt; dim &gt;::space_dimension &gt;',['../namespaceTriangulation_3_01DoFHandler_3_01dim_01_4_1_1dimension_00_01DoFHandler_3_01dim_01_4_1_1space__dimension_01_4.html',1,'']]],
  ['triangulation_3c_20dofhandlertype_3a_3adimension_2c_20dofhandlertype_3a_3aspace_5fdimension_20_3e',['Triangulation&lt; DoFHandlerType::dimension, DoFHandlerType::space_dimension &gt;',['../namespaceTriangulation_3_01DoFHandlerType_1_1dimension_00_01DoFHandlerType_1_1space__dimension_01_4.html',1,'']]],
  ['triaobjects_3c_20internal_3a_3atriangulation_3a_3atriaobject_3c_201_20_3e_20_3e',['TriaObjects&lt; internal::Triangulation::TriaObject&lt; 1 &gt; &gt;',['../namespaceTriaObjects_3_01internal_1_1Triangulation_1_1TriaObject_3_011_01_4_01_4.html',1,'']]],
  ['triaobjects_3c_20internal_3a_3atriangulation_3a_3atriaobject_3c_20dim_20_3e_20_3e',['TriaObjects&lt; internal::Triangulation::TriaObject&lt; dim &gt; &gt;',['../namespaceTriaObjects_3_01internal_1_1Triangulation_1_1TriaObject_3_01dim_01_4_01_4.html',1,'']]],
  ['trilinoswrappers',['TrilinosWrappers',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers.html',1,'']]],
  ['types',['types',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespacetypes.html',1,'']]],
  ['types',['types',['http://www.dealii.org/8.5.0/doxygen/deal.II/namespaceTrilinosWrappers_1_1types.html',1,'TrilinosWrappers']]]
];
